logging:
  level:
    com:
      codigo_morsa: DEBUG

spring:
  application:
    name: myapplication

cloud:
  aws:
    stack:
      auto: false

message: justAnyLocalMachine

dynamoUrl: "http://localhost:4566"
