spring:
  config:
    import: "aws-parameterstore:"

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: us-east-1
    stack:
      auto: true

dynamoUrl: "https://dynamodb.us-east-1.amazonaws.com"
